JSL/teams/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired



class TeamForm(FlaskForm):
    teamname = StringField('Teamname', validators=[DataRequired()])
    captain = StringField('Team Captain', validators=[DataRequired()])
    submit = SubmitField('Register Team')

JSL/main/routes.py
from flask import render_template, request, Blueprint
from JSL.models import Team
from flask_login import login_required


main = Blueprint('main', __name__)


@main.route('/')  
@main.route('/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    teams = Team.query.paginate(page=page, per_page=6)
    return render_template("home.html", teams=teams)

@main.route('/about') 
def about():
    return render_template("about.html",  title= 'About')

JSL/teams/__init__.py
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 17 14:47:33 2020

@author: Daniel Musau
"""

JSL/teams/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from JSL import db
from JSL.models import Team
from JSL.teams.forms import TeamForm

teams = Blueprint('teams', __name__)


@teams.route('/team/new', methods=['GET', 'POST'])
@login_required
def new_team():
    form = TeamForm()
    if form.validate_on_submit():
        team = Team(teamname=form.teamname.data, captain = form.captain.data)
        db.session.add(team)
        db.session.commit()
        flash('Your Team has been registered successfully', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_team.html', title= 'Register Team', form=form, legend= 'Register Team')


@teams.route("/team/<int:team_id>")
def team(team_id):
    team =Team.query.get_or_404(team_id)
    return render_template('team.html', title=team.teamname, team=team)

@teams.route("/team/<int:team_id>/update", methods=['GET', 'POST'])
@login_required
def update_team(team_id):
    team = Team.query.get_or_404(team_id)
    if team.captain != current_user:
        abort(403)
    form = TeamForm()
    if form.validate_on_submit():
        team.teamname = form.teamname.data
        team.captain = form.captain.data
        db.session.commit()
        flash('You have updated your team.', 'success')
        return redirect(url_for('teams.team', team_id=team.id))
    elif request.method == 'GET': 
        form.teamname.data = team.teamname
        form.captain.data = team.captain
    return render_template('create_team.html', title= 'Update Team', form=form, legend= 'Update Team')
    

@teams.route("/team/<int:team_id>/delete", methods=['POST'])
@login_required
def delete_team(team_id):
     team = Team.query.get_or_404(team_id)
     if team.captain != current_user:
        abort(403)
     db.session.delete(team)
     db.session.commit()
     flash('The team has been deleted!', 'success')
     return redirect(url_for('main.home'))

JSL/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from JSL import db, bcrypt
from JSL.models import User, Team
from JSL.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from JSL.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user= User(username=form.username.data, email=form.email.data, password= hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created, you can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form= LoginForm()
    if form.validate_on_submit(): 
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember= form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else: 
            flash("login unsuccessful, check email and password", 'danger')
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
           picture_file = save_picture(form.picture.data) 
           current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated successfully', ' success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title= 'Account', image_file = image_file, form = form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions on how to reset the password to your account.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated, you can now log in', 'success') 
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

JSL/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h1> About </h1>
{%endblock content %}

JSL/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src= {{ image_file }}>
			<div class="media-body">
				<h2 class="account-heading">{{ current_user.username }}</h2>
				<p class="text-secondary">{{ current_user.email }}</p>
			</div>			
		</div>
		<form method="POST" action=" " enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Account Info </legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
					
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class = "form-control-file") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form> 
	</div>
{%endblock content %} 

JSL/templates/create_team.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action=" ">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> {{ legend }}</legend>
				<div class="form-group">
					{{ form.teamname.label(class="form-control-label") }}
					{% if form.teamname.errors %}
						{{ form.teamname(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.teamname.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.teamname(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.captain.label(class="form-control-label") }}
					{% if form.captain.errors %}
						{{ form.captain(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.captain.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.captain(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{%endblock content %}

JSL/templates/home.html
{% extends "layout.html" %}
{% block content %}
	{% for team in teams.items %}
		<article class="media-list">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="#"> Teams </a>
		    </div>
		    <h2><a class="article-teamname" href="{{url_for('teams.team', team_id= team.id )}}">{{ team.teamname }}</a></h2>
		    <p class="article-captain"> Team Captain: {{ team.captain }}</p>
		  </div>
		</article>
	{% endfor %}
	{% for page_num in teams.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if teams.page == page_num %}
				<a class="btn btn-info mb-4 " href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }} </a> 
			{% else %}
				<a class="btn btn-outline-info mb-4 " href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }} </a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{%endblock content %}

JSL/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" style="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title> JKUAT SPORTS LEAGUE - {{ title }}</title>
	{% else %}
		<title> JKUAT SPORTS LEAGUE </title>
	{% endif %}
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Jkuat Sports League</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
	          <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %}
	        		<a class="nav-item nav-link" href="{{url_for('teams.new_team')}}">Register Team</a>
	        		<a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
	        		<a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
	        	{% else %}
	          		<a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
	          		<a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
	          	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% with messages = get_flashed_messages(with_categories=true) %}
	    		{% if messages %}
	    			{% for category, message in messages %}
	    				<div class="alert alert-{{ category }}">
	    					{{ message }}
	    				</div>
	    			{% endfor %}
	    		{% endif %}
	    	{% endwith %}
	    	{% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Fixtures</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Teams</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</main>
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

JSL/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action=" ">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Log In </legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}">Forgot password? </a>
				</small>
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need an account? <a class="ml-2" href="{{ url_for('users.register') }}"> Sign Up Now </a>
		</small>
		

	</div>
{%endblock content %}

JSL/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action=" ">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Join Today </legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
					
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}

						</div>
					{% else %}	
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}"> Sign in </a>
		</small>
		

	</div>
{%endblock content %}

JSL/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action=" ">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Reset Password </legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}	
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{%endblock content %}

JSL/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action=" ">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Reset Password </legend>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}	
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}	
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{%endblock content %}

JSL/templates/team.html
{% extends "layout.html" %}
{% block content %}
		<article class="media-list">
		  <div class="media-body">
		  	<div class="article-metadata">
		      <a class="mr-2" href="#"> Teams </a>
		    	<div>
		    		<a class= "btn  btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('teams.update_team', team_id=team.id) }}">Update</a>
		    		<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"> Deactivate Team </button>
		    	</div>
		    </div>
		    <h2 class="article-teamname">{{ team.teamname }}</h2>
		    <p class="article-captain">{{ team.captain }}</p>
		  </div>
		</article>
	<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="deleteModalLabel">Delete Team?</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        Are you sure you want to delete this team?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <form action="{{ url_for('teams.delete_team', team_id=team.id) }}" method="POST">
	        	<input class="btn btn-danger "type="submit" value="Delete">
	        </form>
	      </div>
	    </div>
	  </div>
</div>
{%endblock content %}